### ISSUE TITLE
Typo in requirements.txt

### ISSUE THREAD

**Issue by therden** [dagraham/etm-mvc#1]
In requirements.txt, reference to prompt-toolkit should be changed to prompt_toolkit.

**Comment by dagraham** [comment]
The file is generated by running

$ pip freeze > requirements.txt

So the current version is actually the one that pip wants.

On Jul 24, 2016, at 3:03 PM, therden <notifications@github.com<mailto:notifications@github.com>> wrote:


In requirement.txt, reference to prompt-toolkit should be changed to prompt_toolkit.

**Comment by therden** [comment]
Then there may be a problem with the info pip access regarding the package, because there is no PyPi package called prompt-toolkit, there is only one called prompt_toolkit.

Or maybe things are even more complicated and confused:  I see that the README.rst file in that library's GitHub repo is internally inconsistent in how it references its name, whereas its readthedocs page consistently uses the underscore form.  

I'll submit an Issue to prompt_toolkit/prompt-toolkit's repo.

**Comment by dagraham** [comment]
If you try pip install -U prompt-toolkit, I think you’ll find that it works.

On Jul 24, 2016, at 4:32 PM, therden <notifications@github.com<mailto:notifications@github.com>> wrote:


Then there may be a problem with the info pip access regarding the package, because there is no PyPi package called prompt-toolkit, there is only one called prompt_toolkit.

Or maybe things are even more complicated and confused: I see that the README.rst file in that library's GitHub repo is internally inconsistent in how it references its name, whereas its readthedocs page consistently uses the underscore form.

I'll submit an Issue to prompt_toolkit/prompt-toolkit's repo.

**Comment by therden** [comment]
Thanks Dan.  I actually had been able to get the library installed and working... I just found/find the discrepancies in the name confusing.

**Comment by dagraham** [comment]
My point was that prompt-toolkit, with the minus sign, works with pip install.

On Jul 24, 2016, at 4:39 PM, therden <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks Dan. I actually had been able to get the library installed and working... I just found/find the discrepancies in the name confusing.

**Comment by therden** [comment]
Understood.
